[MM-820]: Added testcases for multiple server files
mattermost/mattermost-plugin-msteams-meetings pull request #134
Opened 2024-10-04 12:57 UTC by Kshitij-Katiyar

### Summary
Added testcases for server files
- state.go
- user.go
- ExecuteCommand function of command.go

2024-10-09 09:41 UTC, raghavaggarwal2308 requested changes

2024-10-09 09:41 UTC, raghavaggarwal2308 commented on server/command_test.go
> +			response, _ := p.ExecuteCommand(&dummyPluginContext, &tt.commandArgs) // nolint:gosec
Can we remove `nolint:gosec` ?

2024-10-09 09:41 UTC, raghavaggarwal2308 commented on server/state_test.go
> +			mockAPI.On("KVSet", mock.Anything, mock.Anything).Return(tc.returnError)
Can we pas actual arg value for the first argument atleast?

2024-10-10 06:27 UTC, raghavaggarwal2308 approved these changes

2024-12-10 03:18 UTC, wiggin77 approved these changes
LGTM :+1:

2025-01-14 08:04 UTC, merged