Add telemetry
mattermost/mattermost-plugin-msteams-meetings pull request #15
Opened 2020-08-20 11:46 UTC by larkox

#### Summary
Add telemetry to MS Teams Meetings.

The telemetry tracked is:

- Every time a meeting is created
- Every time a meeting is not created because there is another recent meeting
- Every time a meeting creation is forced (even if there is a recent meeting)
- Every time a user sign in into MS Teams Meetings
- Every time a user signs out of MS Teams Meetings

We use telemetry to help improve the quality of Mattermost and to make design decisions for future releases.

This PR will be reviewed by the product team who will confirm which telemetry will actually be used to make those design decisions.

#### Ticket Link
Fix #11

2020-09-08 16:16 UTC, jfrerich approved these changes
Looks good.  There are a lot of other syncing related files included.

2020-09-08 16:16 UTC, jfrerich commented on server/telemetry.go
> +	p.tracker.TrackUserEvent("start_meeting", userID, map[string]interface{}{
Would `meeting_started` work better to match the other keys?  (ex. meeting_duplicated, meetins_forced)

2020-09-09 20:51 UTC, hanzei requested changes
One question about `webapp/junit.xml`

2020-09-09 20:51 UTC, hanzei commented on server/command.go
>  	return "User disconnected from MS Teams Meetings.", nil
Nit:
```suggestion

	p.trackDisconnect(extra.UserId)
	return "User disconnected from MS Teams Meetings.", nil
```

2020-09-09 20:51 UTC, hanzei commented on server/telemetry.go
> +)
nit pick: Add a `type` for these sources

2020-09-09 20:51 UTC, hanzei commented on webapp/junit.xml
> +</testsuites>
The starter template does put this file in `webapp/.gitignore`. Should it ready get added to this repo?

2020-09-15 07:52 UTC, hanzei approved these changes

2020-10-20 15:29 UTC, aaronrothschild approved these changes
LGTM

2020-10-21 21:40 UTC, merged