[GH-53] Add Command autocomplete
mattermost/mattermost-plugin-msteams-meetings pull request #62
Opened 2022-02-13 17:30 UTC by jeromegrosse

#### Summary
* Added command autocomplete for `start` and `disconnect`.
![image](https://user-images.githubusercontent.com/4560899/153767100-e906bdbb-8568-4992-af62-39d9a1b9947c.png)

* Fixed a minor cosmetic error where the a second-level bullet point would mistakenly be used:

 | Before | ![image](https://user-images.githubusercontent.com/4560899/153767312-2307a832-1ac6-4553-922a-256c72dcbed4.png) |
| ---|---|
| After | ![image](https://user-images.githubusercontent.com/4560899/153767332-3a93a993-6022-4f96-ba3d-382ac9a9a0f7.png) |

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-msteams-meetings/issues/53

2022-02-13 17:30 UTC, mattermod commented
Hello @jeromegrosse,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-02-13 17:39 UTC, jeromegrosse commented
Should I also add `help`? I've looked around and some plugins include it and some do not.

2022-02-14 10:42 UTC, larkox commented
@mickmister Can you confirm @jeromegrosse 's question?
Also, do you think we should add (conditionally) the `connect` command?

2022-02-15 15:09 UTC, mickmister reviewed
Yes let's add the `help` command to the autocomplete as well. @jeromegrosse Command autocomplete and help commands are sometimes overlooked as they technically aren't required to implement or test a given feature that involves commands. Unfortunately, this results in inconsistencies among the plugin projects. In general, every command supported should show in the autocomplete and help text.

> Also, do you think we should add (conditionally) the `connect` command?

Yes, makes sense to me to conditionally show the `connect` and `disconnect` commands in the help text.

2022-02-19 16:31 UTC, jeromegrosse commented
@mickmister, I've updated the PR to add the `help` to autocomplete.
However, I am stuck on two points:
* For the conditional `disconnect` I would need to know if the user is connected. I tinkered with `p.store.GetUserInfo(userID)` but I wonder if there's a more straightforward way of know it?
* For the `connect` command: There's no such command currently implemented in the file in this file. I'll have to implement it. I am unsure how to proceed with that.

2022-03-02 05:27 UTC, mickmister commented
> * For the conditional `disconnect` I would need to know if the user is connected. I tinkered with `p.store.GetUserInfo(userID)` but I wonder if there's a more straightforward way of know it?

The store is where we persist info on connected users, so this seems like the only way to know if the user is connected.

> * For the `connect` command: There's no such command currently implemented in the file in this file. I'll have to implement it. I am unsure how to proceed with that.

We can just show a connect link to the user when they run the `connect` command:

```go
siteURL, err := p.getSiteURL()
// handle error

// oAuthMessage is already defined for you in package scope
oauthMsg := fmt.Sprintf(oAuthMessage, siteURL, extra.ChannelId)

return p.postCommandResponse(extra, oauthMsg)
```

2022-03-13 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-03-24 12:23 UTC, dipak-demansol requested changes
1) When i Use **/mstmeetings help xyz** then its ignore the extra parameter and give me the right output but when i use **/mstmeetings start xyz** or **/mstmeetings disconnect xyz** then it gives me the validation as  **"Too many parameters."** but i expect start & disconnect should work same as help, it should not give the validation, it should ignore The Extra parameter.

2022-03-24 12:24 UTC, dipak-demansol commented
@jeromegrosse :point_up:

2022-03-25 11:25 UTC, dipak-demansol commented
> 1. When i Use **/mstmeetings help xyz** then its ignore the extra parameter and give me the right output but when i use **/mstmeetings start xyz** or **/mstmeetings disconnect xyz** then it gives me the validation as  **"Too many parameters."** but i expect start & disconnect should work same as help, it should not give the validation, it should ignore The Extra parameter.

@larkox This Point :point_up: Should be Fixed on this PR or Should i  Create new ticket?

2022-03-26 08:26 UTC, larkox commented
@dipak-demansol A new ticket, please. It is not really related to the scope of the issue.

2022-03-26 09:39 UTC, dipak-demansol approved these changes
LGTM

2022-04-07 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-04-07 13:50 UTC, larkox approved these changes
Missing the conditional (not sure where we ended with that) but apart of that LGTM. Thanks!

2022-04-25 05:03 UTC, mickmister requested changes
Thanks @jeromegrosse! I have one more request regarding the order of the shown commands. Otherwise LGTM :+1:

2022-04-25 05:03 UTC, mickmister commented on server/command.go
> +	command.AddCommand(help)
Does this put the `help` command at the top of the list? If so, can we move it to the bottom? The order should be:

- start
- disconnect
- help

Also, we should list `help` in the original list on line 43

2022-04-25 05:03 UTC, mickmister commented on server/command.go
> +		AutoCompleteDesc:     "Available commands: help, start, disconnect",
We should put `help` last here too

```suggestion
		AutoCompleteDesc:     "Available commands: help, start, disconnect",
```

2022-04-25 05:03 UTC, mickmister commented on server/command.go
> +		"* |/mstmeetings disconnect| - Disconnect from Mattermost. \n"
We should put `help` last here too

2022-04-25 05:03 UTC, mickmister commented on server/command.go
> +		"* |/mstmeetings disconnect| - Disconnect from Mattermost. \n"
```suggestion
	commandHelp = "###### Mattermost MS Teams Meetings Plugin - Slash Command Help\n" +
		"* |/mstmeetings help| - Display this help text. \n" +
		"* |/mstmeetings start| - Start an MS Teams meeting. \n" +
		"* |/mstmeetings disconnect| - Disconnect your Mattermost account from MS Teams. \n"
```

2023-02-04 21:42 UTC, hanzei commented
Closing as inactive

2023-02-04 21:42 UTC, closed without merging